name: Lint

on: ["push", "pull_request"]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: 🧼 lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: '**/*.md .github/**/*.md'

  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🧼 lint renovate config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
        with:
          config_file_path: 'renovate.json'
