name: .NET Build & Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x
      - name: Restore Dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --configuration Release --no-restore
      - name: Unit Tests
        run: |
          cd ./tests/Unit/
          dotnet test --no-restore -nodereuse:false \
            /p:UseSharedCompilation=false \
            /p:UseRazorBuildServer=false \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=/home/runner/work/Gossip/ \
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: /home/runner/work/Gossip/coverage.opencover.xml
          fail_ci_if_error: true
